--- 
version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.1.3
  aws-s3: circleci/aws-s3@2.0.0
jobs: 
  test: 
    docker: 
      - 
        environment: 
          CHROME_BIN: /usr/bin/google-chrome
        # Note: Environment variables set in this way are not available to steps run within the container, 
        # they are only available to the entrypoint/command run by the container. 
        # By default, CircleCI will ignore the entrypoint for a job’s primary container. 
        # For the primary container’s environment variables to be useful, you will need to preserve the entrypoint. 
        # For more information, see the adding an entrypoint section of the Custom Images guide.
        image: "cimg/node:10.24.0-browsers"
    steps: 
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - 
        run: 
          command: |
              google-chrome --version
              chromedriver --version
          name: "Check install"
      - checkout
      - 
        run: 
          command: "echo ${CIRCLE_BRANCH}"
          name: "Show current branch"
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package-lock.json\" }}"
            - v1-dependencies-
      - 
        run: 
          command: "npm install"
          name: "Install local dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"package-lock.json\" }}"
          paths: 
            - node_modules
      - 
        run: 
          command: "npm run lint:ci"
          name: Linting
      - 
        run: 
          command: "npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
          name: Testing
      - 
        run: 
          command: "npm run e2e -- --protractor-config=protractor-ci.conf.js"
          name: "End to End Test"
    working_directory: ~/ngx-portal
  push_dev: 
    docker: 
      - 
        image: "cimg/node:10.24.0"
    environment:
      NG_DEPLOY_AWS_BUCKET: dev-sg.portal.hocvienconggiao.com
      NG_DEPLOY_AWS_REGION: ap-southeast-1
    steps:
      - checkout
      - 
        run: 
          command: "echo ${CIRCLE_BRANCH}"
          name: "Show current branch"
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package-lock.json\" }}"
            - v1-dependencies-
      - 
        run: 
          command: "npm install"
          name: "Install local dependencies"
      - 
        run: 
          command: "npx ng build --configuration development"
          name: "Build ng app for DEV env"
      - 
        aws-s3/sync:
          arguments: |
              --delete \
              --acl public-read \
              --cache-control 'max-age=604800' \
              --exclude *.html
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: NG_DEPLOY_AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: s3://dev-sg.portal.hocvienconggiao.com
      - 
        aws-s3/sync:
          arguments: |
              --delete \
              --acl public-read \
              --cache-control 'no-cache'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: NG_DEPLOY_AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: s3://dev-sg.portal.hocvienconggiao.com          
    working_directory: ~/ngx-portal    
  push_prod: 
    docker: 
      - 
        image: "cimg/node:10.24.0"
    environment:
      NG_DEPLOY_AWS_BUCKET: prod-sg.portal.hocvienconggiao.com
      NG_DEPLOY_AWS_REGION: ap-southeast-1
    steps:
      - checkout
      - 
        run: 
          command: "echo ${CIRCLE_BRANCH}"
          name: "Show current branch"
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package-lock.json\" }}"
            - v1-dependencies-
      - 
        run: 
          command: "npm install"
          name: "Install local dependencies"
      - 
        run: 
          command: "npx ng build --configuration production"
          name: "Build ng app for PROD env"
      - 
        aws-s3/sync:
          arguments: |
              --delete \
              --acl public-read \
              --cache-control 'max-age=604800' \
              --exclude *.html              
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: NG_DEPLOY_AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: s3://prod-sg.portal.hocvienconggiao.com
      - 
        aws-s3/sync:
          arguments: |
              --delete \
              --acl public-read \
              --cache-control 'no-cache'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: NG_DEPLOY_AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: s3://prod-sg.portal.hocvienconggiao.com
          
    working_directory: ~/ngx-portal    
    
workflows: 
  test_and_push: 
    jobs: 
      - test
      - push_dev:
          context: build_push
          filters: 
            branches: 
              only: 
                - dev           
                # - /test\/.*/
                # The above line of code causes the job push_dev to only be run when the branch being built starts with "test/" in it.
          requires: 
            - test
      - push_prod:
          context: build_push
          filters: 
            branches: 
              only: 
                - prod
                # - /test\/.*/
                # The above line of code causes the job push_dev to only be run when the branch being built starts with "test/" in it.
          requires: 
            - test            
  version: 2
