version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
    # The test job
    test:
        working_directory: ~/ngx-portal
        docker:
            - image: cimg/node:10.24.0-browsers
              environment:
                CHROME_BIN: /usr/bin/google-chrome
                CI: "true"
        steps:
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                command: |
                  google-chrome --version
                  chromedriver --version
                name: Check install
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "skeleton/v11/package-lock.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: cd skeleton/v11 && npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "skeleton/v11/package-lock.json" }}
                paths:
                    - skeleton/v11/node_modules
            # Lint the source code
            - run:
                name: Linting
                command: cd skeleton/v11 && npm run lint
            # Test the source code
            - run:
                name: Testing
                command: cd skeleton/v11 && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            # End to End test
            - run:
                name: End to End Test
                command: cd skeleton/v11 && npm run e2e -- --protractor-config=protractor-ci.conf.js

workflows:
    version: 2
    # the test workflow
    test_workflow:
        jobs:
            - test #:
                # filters:
                #     branches:
                #         only:
                #             - develop
                #             - staging
                #             - master
